name: "CD/DVD Reader"
description: |
  "Reads DVDs and CDs as mp4 and mp3 files respectively. 
  Great for users with Plex who want to backjup their digital library."
version: "1.0.16"
slug: "cd_reader"
init: false
startup: services
image: eddiewebb/ha-cd-reader-amd64
arch:
  - amd64
options:
  mp3_path: /media/music
  mp4_path: /media/movies
  ssh:
    username: hassio
    password: ""
    authorized_keys: []
    sftp: false
    compatibility_mode: false
    allow_agent_forwarding: false
    allow_remote_port_forwarding: false
    allow_tcp_forwarding: false
  zsh: false
  share_sessions: false
  packages: []
  init_commands: []
schema:
  mp3_path: str
  mp4_path: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssh:
    username: str
    password: password
    authorized_keys:
      - str
    sftp: bool
    compatibility_mode: bool
    allow_agent_forwarding: bool
    allow_remote_port_forwarding: bool
    allow_tcp_forwarding: bool
  zsh: bool
  share_sessions: bool
  packages:
    - str
  init_commands:
    - str
ingress: true
ports:
  22/tcp: 24
ports_description:
  22/tcp: SSH server port (make empty to disable)
docker_api: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
privileged: 
  - NET_ADMIN
  - SYS_ADMIN
  - DAC_READ_SEARCH
map:
  - media:rw
  - share:rw
boot: manual
environment:
  PGID: '0'
  PUID: '0'
devices:
  - /dev/sr0
apparmor: false
uart: true
