# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: nocodb add-on
version: "1.0.1"
slug: nocodb
description: nocodb add-on
url: "https://github.com/eddiewebb/home-assistant-addons/tree/main/nocodb"
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "eddiewebb/ha-nocodb-{arch}"
ports:
  8080/tcp: 8005
